version: "3.9"

services:
  project:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - ./media:/application/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "17874:17874" 

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: mhitaryan.fortech@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 15432
    ports:
      - 15432:15432
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  pgadmin:
